package com.gpetuhov.android.sampledagger3.application

import android.app.Application
import com.gpetuhov.android.sampledagger3.application.dagger.components.*
import com.gpetuhov.android.sampledagger3.application.dagger.modules.AppModule

// Application class is used to control lifecycle of the components.

// Don't forget to use it in the manifest!

// DaggerAppComponent, DaggerCalculatorComponent, DaggerAdderComponent
// and DaggerSubtractorComponent are generated by Dagger.

class App : Application() {

    companion object {
        var appComponent: AppComponent? = null
        private var calculatorComponent: CalculatorComponent? = null
        private var adderComponent: AdderComponent? = null
        private var subtractorComponent: SubtractorComponent? = null

        // Components are instantiated as singletons
        fun getCalculatorComponent(): CalculatorComponent? {
            if (calculatorComponent == null) {
                // CalculatorComponent is created upon AppComponent,
                // as it is dependent on it.
                calculatorComponent = DaggerCalculatorComponent.builder()
                    .appComponent(appComponent)
                    .build()
            }
            return calculatorComponent
        }

        // Lifecycle of the components is controlled manually
        fun clearCalculatorComponent() {
            // When the component is null, it can be garbage collected
            // along with the classes, instantiated with the corresponding scope.
            calculatorComponent = null
        }

        fun getAdderComponent(): AdderComponent? {
            if (adderComponent == null) {
                // AdderComponent is created upon CalculatorComponent
                adderComponent = DaggerAdderComponent.builder()
                    .calculatorComponent(calculatorComponent)
                    .build()
            }
            return adderComponent
        }

        fun clearAdderComponent() {
            adderComponent = null
        }

        fun getSubtractorComponent(): SubtractorComponent? {
            if (subtractorComponent == null) {
                // SubtractorComponent is also created upon CalculatorComponent
                subtractorComponent = DaggerSubtractorComponent.builder()
                    .calculatorComponent(calculatorComponent)
                    .build()
            }
            return subtractorComponent
        }

        fun clearSubtractorComponent() {
            subtractorComponent = null
        }
    }

    override fun onCreate() {
        super.onCreate()
        appComponent = DaggerAppComponent.builder()
            .appModule(AppModule())     // this line can be omitted
            .build()
    }
}